'use client'

import {
  Briefcase, Code, Globe, Buildings,
  GraduationCap, Brain
} from "@phosphor-icons/react";
import type { Locale } from "@/lib/i18n";

const milestones = {
  "zh-TW": [
    {
      year: "2026",
      period: "2026-02 → 至今",
      title: "中國信託（法金 AI）",
      subtitle: "高級架構師",
      icon: <Brain className="w-4 h-4" weight="bold" />,
      color: "from-[color:var(--accent)] to-[color:var(--fg-2)]",
      descriptions: [
        "AI Platform 設計與架構規劃",
        "RAG Flow 架構設計與實作",
        "AI Agent 開發與協作流程設計",
        "知識工程與上下文工程系統設計",
        "整體 AI 服務串接與落地部署",
      ],
      tags: ["AI Platform", "RAG", "AI Agent", "K8s", "Cloud", "LLM"],
      side: "right",
      isActive: true,
    },
    {
      year: "2025",
      period: "2025-03 → 2025-09",
      title: "優配科技 (Universal Processing LLC)",
      subtitle: "資深軟體工程師",
      icon: <Buildings className="w-4 h-4" weight="bold" />,
      color: "from-[color:var(--accent)] to-[color:var(--fg-2)]",
      descriptions: [
        "CRM / Onboarding / 分潤 / POS 系統開發",
        "POS 系統體驗設計主導，統一操作與交付節奏",
        "參與跨國團隊開發與部署流程",
        "多系統整合與第三方服務串接",
      ],
      tags: [".NET", "Node.js", "React", "AWS", "CRM"],
      side: "left",
    },
    {
      year: "2025",
      period: "2025",
      title: "8plus 工程諮詢平台",
      subtitle: "個人品牌站與預約入口上線",
      icon: <Globe className="w-4 h-4" weight="bold" />,
      color: "from-[color:var(--accent)] to-[color:var(--fg-2)]",
      descriptions: [
        "以 Next.js 15 + Velite 建置工程諮詢品牌站",
        "整合線上預約與雙語內容管線",
        "統一企業級設計語言與轉換動線",
        "建立可持續更新的技術內容與專案展示",
      ],
      tags: ["Next.js", "Vercel", "Google Calendar", "Velite"],
      side: "right",
    },
    {
      year: "2024",
      period: "2024-06 → 2025-03",
      title: "台達電子",
      subtitle: "資深軟體工程師",
      icon: <Briefcase className="w-4 h-4" weight="bold" />,
      color: "from-[color:var(--accent)] to-[color:var(--fg-2)]",
      descriptions: [
        "Java 專案重構為 .NET Core 8，容器化部署至 Kubernetes",
        "串接 SAP 系統，實現企業級資料交換",
        "建立完善的監控機制（Prometheus + Grafana）",
        "系統效能優化與技術債清理",
      ],
      tags: [".NET Core 8", "K8s", "SAP", "Prometheus", "Java"],
      side: "left",
    },
    {
      year: "2024",
      period: "2024",
      title: "Vue 3 作品集迭代",
      subtitle: "商業導向品牌呈現",
      icon: <Code className="w-4 h-4" weight="bold" />,
      color: "from-[color:var(--accent)] to-[color:var(--fg-2)]",
      descriptions: [
        "以商業導向為主的作品集設計",
        "強調品牌凝聚力與專案價值呈現",
        "注重資訊階層、視覺節奏與轉換動線",
      ],
      tags: ["Vue 3", "UI/UX", "Tailwind CSS"],
      side: "right",
    },
    {
      year: "2023",
      period: "2023-09 → 2024-05",
      title: "中國信託（個人金融）",
      subtitle: "軟體工程師",
      icon: <Buildings className="w-4 h-4" weight="bold" />,
      color: "from-[color:var(--accent)] to-[color:var(--fg-2)]",
      descriptions: [
        "個人金融部門內部系統開發與維運",
        "保險代理人系統開發與優化",
        "OCP（OpenShift Container Platform）上開發與部署",
        "微服務架構導入與系統現代化",
      ],
      tags: [".NET", "OCP", "K8s", "金融系統"],
      side: "left",
    },
    {
      year: "2021",
      period: "2021-03 → 2023-02",
      title: "91APP 九易宇軒",
      subtitle: "資深軟體工程師",
      icon: <Buildings className="w-4 h-4" weight="bold" />,
      color: "from-[color:var(--accent)] to-[color:var(--fg-2)]",
      descriptions: [
        "Data Team 推播中心微服務架構設計與開發",
        "每小時 300-500 萬推播發送量的高吞吐系統",
        "使用 EKS + GCP + RabbitMQ + SQS 多雲混合架構",
        "高流量系統穩定維運與效能調校",
      ],
      tags: ["EKS", "RabbitMQ", "SQS", "GCP", "微服務"],
      side: "right",
    },
    {
      year: "2021",
      period: "2021",
      title: "Angular 作品集",
      subtitle: "企業系統開發期間",
      icon: <Code className="w-4 h-4" weight="bold" />,
      color: "from-[color:var(--accent)] to-[color:var(--fg-2)]",
      descriptions: [
        "震旦集團任職期間累積的前端工程實務",
        "模組化前端架構、支付流程整合與樣式工程化",
      ],
      tags: ["Angular", "PayPal", "Sass"],
      side: "left",
    },
    {
      year: "2019",
      period: "2019-12 → 2021-03",
      title: "震旦集團",
      subtitle: "資深軟體工程師",
      icon: <Briefcase className="w-4 h-4" weight="bold" />,
      color: "from-[color:var(--accent)] to-[color:var(--fg-2)]",
      descriptions: [
        "VB .NET 轉型 .NET Framework 4.7 現代化改造",
        "前後端分離架構設計（Angular + .NET Web API）",
        "CI/CD 自動化部署流程導入",
        "Power BI 數據報表開發、Checkmarx 資安掃描導入",
      ],
      tags: ["Angular", ".NET", "Power BI", "CI/CD"],
      side: "right",
    },
    {
      year: "2019",
      period: "2019",
      title: "互動式作品集",
      subtitle: "碩士研究期間",
      icon: <Code className="w-4 h-4" weight="bold" />,
      color: "from-[color:var(--accent)] to-[color:var(--fg-2)]",
      descriptions: [
        "以 JS/CSS 實作互動型個人作品集",
        "聚焦資訊層次、動效節制與閱讀節奏",
      ],
      tags: ["VanillaJS", "CSS Animation", "Sass", "Gulp"],
      side: "left",
    },
    {
      year: "2018",
      period: "2018-07",
      title: "NCTU 交通大學 — 分子醫學與生物工程研究所",
      subtitle: "碩士畢業（GPA 3.98）",
      icon: <GraduationCap className="w-4 h-4" weight="bold" />,
      color: "from-[color:var(--accent)] to-[color:var(--fg-2)]",
      descriptions: [
        "跨領域從食品科學轉向資訊工程與分子醫學",
        "使用 R / Python 進行生物資訊分析",
        "碩士論文開發慢性腎臟病檢驗工具",
        "選修資工課程，完成前後端專案獲得教授肯定",
      ],
      tags: ["NCTU", "Python", "R", "Bioinformatics"],
      side: "right",
    },
    {
      year: "2012",
      period: "2012-09",
      title: "NTOU 海洋大學 — 食品科學系",
      subtitle: "學士畢業（GPA 3.74）",
      icon: <GraduationCap className="w-4 h-4" weight="bold" />,
      color: "from-[color:var(--accent)] to-[color:var(--fg-2)]",
      descriptions: [
        "打下科學研究方法與數據分析基礎",
        "自學網頁開發，建立程式設計基礎",
      ],
      tags: ["NTOU", "食品科學", "自學開發"],
      side: "left",
    },
  ],
  "en": [
    {
      year: "2026",
      period: "2026-02 → Present",
      title: "CTBC Bank (Corporate Banking AI)",
      subtitle: "Senior Architect",
      icon: <Brain className="w-4 h-4" weight="bold" />,
      color: "from-[color:var(--accent)] to-[color:var(--fg-2)]",
      descriptions: [
        "AI Platform architecture & design",
        "RAG Flow architecture design & implementation",
        "AI Agent development & orchestration",
        "Knowledge & Context Engineering system design",
        "End-to-end AI service integration & deployment",
      ],
      tags: ["AI Platform", "RAG", "AI Agent", "K8s", "Cloud", "LLM"],
      side: "right",
      isActive: true,
    },
    {
      year: "2025",
      period: "2025-03 → 2025-09",
      title: "Universal Processing LLC",
      subtitle: "Senior Software Engineer",
      icon: <Buildings className="w-4 h-4" weight="bold" />,
      color: "from-[color:var(--accent)] to-[color:var(--fg-2)]",
      descriptions: [
        "CRM / Onboarding / Revenue Share / POS system development",
        "POS UIX Lead Designer",
        "Cross-border team collaboration & deployment",
        "Multi-system integration & third-party API orchestration",
      ],
      tags: [".NET", "Node.js", "React", "AWS", "CRM"],
      side: "left",
    },
    {
      year: "2025",
      period: "2025",
      title: "8plus consulting platform",
      subtitle: "Brand site and booking launch",
      icon: <Globe className="w-4 h-4" weight="bold" />,
      color: "from-[color:var(--accent)] to-[color:var(--fg-2)]",
      descriptions: [
        "Built engineering consulting brand site with Next.js 15 + Velite",
        "Integrated online booking and bilingual content pipeline",
        "Unified enterprise design language and conversion flow",
        "Established sustainable technical content and project showcase",
      ],
      tags: ["Next.js", "Vercel", "Google Calendar", "Velite"],
      side: "right",
    },
    {
      year: "2024",
      period: "2024-06 → 2025-03",
      title: "Delta Electronics",
      subtitle: "Senior Software Engineer",
      icon: <Briefcase className="w-4 h-4" weight="bold" />,
      color: "from-[color:var(--accent)] to-[color:var(--fg-2)]",
      descriptions: [
        "Refactored Java project to .NET Core 8 with K8s deployment",
        "Integrated SAP for enterprise data exchange",
        "Built monitoring infrastructure (Prometheus + Grafana)",
        "System performance optimization & tech debt reduction",
      ],
      tags: [".NET Core 8", "K8s", "SAP", "Prometheus", "Java"],
      side: "left",
    },
    {
      year: "2024",
      period: "2024",
      title: "Vue 3 portfolio iteration",
      subtitle: "Business-oriented brand presentation",
      icon: <Code className="w-4 h-4" weight="bold" />,
      color: "from-[color:var(--accent)] to-[color:var(--fg-2)]",
      descriptions: [
        "Business-oriented portfolio design",
        "Brand cohesion & project value presentation",
        "Information hierarchy & visual rhythm",
      ],
      tags: ["Vue 3", "UI/UX", "Tailwind CSS"],
      side: "right",
    },
    {
      year: "2023",
      period: "2023-09 → 2024-05",
      title: "CTBC Bank (Personal Banking)",
      subtitle: "Software Engineer",
      icon: <Buildings className="w-4 h-4" weight="bold" />,
      color: "from-[color:var(--accent)] to-[color:var(--fg-2)]",
      descriptions: [
        "Internal system development for personal banking division",
        "Insurance agency system development & optimization",
        "Development & deployment on OpenShift Container Platform",
        "Microservices architecture migration",
      ],
      tags: [".NET", "OCP", "K8s", "Banking"],
      side: "left",
    },
    {
      year: "2021",
      period: "2021-03 → 2023-02",
      title: "91APP",
      subtitle: "Senior Software Engineer",
      icon: <Buildings className="w-4 h-4" weight="bold" />,
      color: "from-[color:var(--accent)] to-[color:var(--fg-2)]",
      descriptions: [
        "Push notification microservices architecture & development",
        "3-5M hourly push notifications throughput",
        "Hybrid cloud with EKS + GCP + RabbitMQ + SQS",
        "High-traffic system operation & performance tuning",
      ],
      tags: ["EKS", "RabbitMQ", "SQS", "GCP", "Microservices"],
      side: "right",
    },
    {
      year: "2021",
      period: "2021",
      title: "Angular portfolio",
      subtitle: "Enterprise systems period",
      icon: <Code className="w-4 h-4" weight="bold" />,
      color: "from-[color:var(--accent)] to-[color:var(--fg-2)]",
      descriptions: [
        "Frontend engineering practice during AURORA Group tenure",
        "Modular frontend architecture, payment integration, and styling systems",
      ],
      tags: ["Angular", "PayPal", "Sass"],
      side: "left",
    },
    {
      year: "2019",
      period: "2019-12 → 2021-03",
      title: "AURORA Group (震旦集團)",
      subtitle: "Senior Software Engineer",
      icon: <Briefcase className="w-4 h-4" weight="bold" />,
      color: "from-[color:var(--accent)] to-[color:var(--fg-2)]",
      descriptions: [
        "Modernized VB .NET legacy to .NET Framework 4.7",
        "Frontend-backend separation (Angular + .NET Web API)",
        "Implemented CI/CD automated deployment",
        "Power BI reporting & Checkmarx security scanning",
      ],
      tags: ["Angular", ".NET", "Power BI", "CI/CD"],
      side: "right",
    },
    {
      year: "2019",
      period: "2019",
      title: "Interactive portfolio",
      subtitle: "Graduate research period",
      icon: <Code className="w-4 h-4" weight="bold" />,
      color: "from-[color:var(--accent)] to-[color:var(--fg-2)]",
      descriptions: [
        "Built an interactive personal portfolio with JS/CSS",
        "Focused on information hierarchy, restrained motion, and reading rhythm",
      ],
      tags: ["VanillaJS", "CSS Animation", "Sass", "Gulp"],
      side: "left",
    },
    {
      year: "2018",
      period: "2018-07",
      title: "NCTU — Institute of Molecular Medicine & Bioengineering",
      subtitle: "M.S. Graduated (GPA 3.98)",
      icon: <GraduationCap className="w-4 h-4" weight="bold" />,
      color: "from-[color:var(--accent)] to-[color:var(--fg-2)]",
      descriptions: [
        "Cross-disciplinary pivot from Food Science to CS",
        "Bioinformatics analysis using R / Python",
        "Thesis: CKD diagnostic tool development",
        "Built full-stack projects recognized by professors",
      ],
      tags: ["NCTU", "Python", "R", "Bioinformatics"],
      side: "right",
    },
    {
      year: "2012",
      period: "2012-09",
      title: "NTOU — Department of Food Science",
      subtitle: "B.S. Graduated (GPA 3.74)",
      icon: <GraduationCap className="w-4 h-4" weight="bold" />,
      color: "from-[color:var(--accent)] to-[color:var(--fg-2)]",
      descriptions: [
        "Scientific research methodology foundation",
        "Self-taught HTML/CSS/JS - start of programming journey",
      ],
      tags: ["NTOU", "Food Science", "Self-learning"],
      side: "left",
    },
  ],
};

export function getPathMilestones(locale: Locale) {
  return milestones[locale] ?? milestones.en
}
